import React, { useState } from "react";
import BasicTable from "../components/BasicTable";
import ViewAllListings from "../components/ViewAllListings";

const DocumentationPage = () => {
	const [showDetails, setShowDetails] = useState(false);
	const dimensionRows = [
		{ id: "generated by system" },
		{ businessName: "official name or descriptive name" },
		{
			businessDescription:
				"description of key variables and explanation for their usage",
		},
		{
			businessIndustry: [
				"Wholesale trade",
				"Retail trade",
				"Accommodation and food services",
				"Transport, postal and warehousing",
				"Rental, hiring and real estate services",
				"Education and training (private)",
				"Health care and social assistance (private)",
				"Arts and recreation services",
				"Other services",
			],
		},
		{
			businessDivision: [
				"Motor vehicle and motor vehicle parts retailing",
				"Fuel retailing",
				"Food retailing",
				"Other store-based retailing",
				"Non-store retailing and retail commission-based buying and/or selling",
				"Accommodation",
				"Food and beverage services",
				"Rental and hiring services (except real estate)",
				"Real estate services",
				"Nail, Hair, and Skin care service",
			],
		},
		{
			businessModel: [
				"Owner Operated",
				"Mixed Management",
				"Owner Administrated",
				"Under Management",
				"Franchise",
			],
		},
		{
			businessSize: [
				"Small (1 to 4 employees)",
				"Medium (5 to 19 employees)",
				"Large (20+ employees)",
			],
		},
		{ locationState: ["NSW", "VIC", "QLD", "SA", "WA", "TAS", "NT", "ACT"] },
		{ locationSuburb: "Suburb Name" },
		{ locationPostCode: "Post Code (XXXX)" },
		{ askingPrice: "Dollar amount (AUD)" },
		{ salePrice: "Dollar amount (AUD)" },
		{ annualRevenue: "Dollar amount (AUD)" },
		{ annualOutgoings: "Dollar amount (AUD)" },
		{ annualWages: "Dollar amount (AUD)" },
		{ annualRent: "Dollar amount (AUD)" },
		{ annualProfit: "Dollar amount (AUD)" },
		{ gstValue: "Percentage % or 0 (included)" },
		{
			savIncluded: "1 (included) or 0 (not included)",
		},
		{
			savValue: "Dollar amount (AUD) or 0 (if not included, will be estimated)",
		},
		{ yieldIncluded: "1 (included) or 0 (not included)" },
		{ yieldValue: "Percentage (%) or 0 (if not included, will be estimated" },
		{ sgaValue: "Percentage (%) or 0" },
		{ tradingDays: "1 to 7 trading days" },
		{ listingStatus: "Available (default) or Sold" },
		{ dateAdded: "DD/MM/YYYY" },
		{ listingVerified: "Verified or Pending (default)" },
		{ listingUrl: "link to origin listing if available elsewhere" },
	];
	return (
		<section className="text-white lg:w-250 mx-auto px-10">
			<div className="font-writing text-center">
				<p className="text-4xl font-bold py-12">Documentation</p>

				<p className="text-lg font-semibold text-left my-2">
					A. Data Collection
				</p>

				<p className="text-lg font-base text-left mb-2 ml-2">
					I. Business Listings
				</p>
				<p className="text-md font-light text-left mb-2 ml-4">Data Sources:</p>
				<ul className="text-md font-light text-left mb-2 ml-8 list-disc">
					<li>Seek Business: seekbusiness.com.au</li>
					<li>BusinessesForSale.com: australia.businessesforsale.com</li>
				</ul>
				<p className="text-md font-light text-left mb-2 ml-4">
					Inclusion Criteria:
				</p>
				<ul className="text-md font-light text-left mb-2 ml-8 list-disc">
					<li>
						Listings must disclose at least four out of the five key financial
						indicators: Revenue, Rent, Outgoings, Wages, and Net Profit. The
						fifth may be derived where feasible.
					</li>
					<li>
						Business descriptions must be sufficiently detailed to facilitate
						comprehension of the operational model, with essential data on
						industry classification, location, and structural setup.
					</li>
					<li>
						Supplementary variables that enhance model precision are also
						collected, including: GST status, Stock at Valuation (SAV), rent
						escalation terms, number of employees, Cost of Goods Sold (COGS),
						and administration fees (especially in franchise structures).
					</li>
				</ul>

				<p className="text-lg font-base text-left mb-2">II. Economic Factors</p>
				<p className="text-md font-light text-left mb-2 ml-4">Data Sources:</p>
				<ul className="text-md font-light text-left mb-2 ml-8 list-disc">
					<li>Australian Bureau of Statistics (ABS): www.abs.gov.au</li>
					<li>Seek: www.seek.com.au</li>
				</ul>
				<p className="text-md font-light text-left mb-2 ml-4">
					Selected Economic Indicators:
				</p>
				<ul className="text-md font-light text-left mb-2 ml-8 list-disc">
					<li>
						Consumer Price Index (CPI): Applied to estimate growth in general
						Outgoings
					</li>
					<li>
						Rental CPI: Used to benchmark rental growth across capital cities
					</li>
					<li>Wage Price Index (WPI): Used to adjust wage projections</li>
					<li>
						Industry-specific Sales Data (ABS): Informing revenue trends and
						estimating sector-wide SAV
					</li>
					<li>
						Owner Salary Benchmarks: Used to infer typical wage costs across
						business models (Source: Seek)
					</li>
				</ul>
				<p className="text-md font-light text-left mb-2 ml-4">
					Note: When listings lack sufficient economic information, the model
					applies these standardized benchmarks. (ABS, 2024)
				</p>

				<p className="text-lg font-base text-left mb-2">III. Data Processing</p>
				<p className="text-md font-light text-left mb-2 ml-4">
					All monetary variables are normalized to annual figures. Only verified
					data from the most recent complete financial year are used;
					projections are excluded.
				</p>
				<p className="text-md font-light text-left mb-2 ml-4">
					To smooth year-to-year fluctuations, Compound Annual Growth Rate
					(CAGR) is employed for all projections.
				</p>
				<p className="text-md font-light text-left mb-2 ml-4">
					Economic indicators are compiled over a 5-year historical window,
					irrespective of reporting cycles.
				</p>
				<p className="text-md font-light text-left mb-2 ml-4">
					Input dimensions are standardized prior to integration into the model
					to ensure internal consistency.
				</p>

				{showDetails ? (
					<div className="py-4">
						<button
							className="italic bg-transparent rounded-lg hover:bg-gray-900 text-blue-500 p-2"
							onClick={() => setShowDetails(!showDetails)}
						>
							See less
						</button>
						<BasicTable rows={dimensionRows} />
						<button
							className="mt-4 italic bg-transparent rounded-lg hover:bg-gray-900 text-blue-500 p-2"
							onClick={() => setShowDetails(!showDetails)}
						>
							See less
						</button>
					</div>
				) : (
					<div className="py-4">
						<button
							className="italic bg-transparent rounded-lg hover:bg-gray-900 text-blue-500 p-2 hover:hover:cursor-pointer"
							onClick={() => setShowDetails(!showDetails)}
						>
							All Dimensions of a Standardized Business Listing
						</button>
					</div>
				)}

				<p className="text-lg font-semibold text-left my-2">
					B. Discounted Cash Flow (DCF) Model
				</p>

				<p className="text-lg font-base text-left mb-2">I. Business Model</p>
				<p className="text-md font-light text-left mb-2 ml-4">
					The base year (Year 0) utilizes actual financial figures obtained from
					listings.
				</p>
				<p className="text-md font-light text-left mb-2 ml-4">
					Forward projections are informed by macroeconomic indicators and
					historical growth data.
				</p>

				<p className="text-lg font-base text-left mb-2">
					II. Initial Investment
				</p>
				<p className="text-md font-light text-left mb-2 ml-4">
					Initial investment comprises the asking price plus estimated SAV and
					GST, if such costs are not explicitly stated.
				</p>

				<p className="text-lg font-base text-left mb-2">
					III. Operating Cash Flow
				</p>
				<ul className="text-md font-light text-left mb-2 ml-8 list-disc">
					<li>EBITDA</li>
					<li>- Depreciation</li>
					<li>EBIT</li>
					<li>- Interest</li>
					<li>- Tax</li>
					<li>Net Income</li>
					<li>+ Depreciation</li>
					<li>Operating Cash Flow</li>
					<li>- Net Working Capital</li>
					<li>Net Operating Cash Flow</li>
				</ul>

				<p className="text-lg font-base text-left mb-2">
					IV. Incremental Cash Flow
				</p>
				<p className="text-md font-light text-left mb-2 ml-4">
					Required return rates vary by management structure, based on
					risk-adjusted expectations (Damodaran, 2022):
				</p>
				<ul className="text-md font-light text-left mb-2 ml-8 list-disc">
					<li>Owner-Operated: 20%</li>
					<li>Mixed Management: 18%</li>
					<li>Owner-Administered: 15%</li>
					<li>Under Full Management: 12%</li>
					<li>Franchise Model: 10%</li>
				</ul>

				<p className="text-lg font-base text-left mb-2">
					V. Valuation and Verdict
				</p>
				<p className="text-md font-light text-left mb-2 ml-4">
					Valuation is based on Net Present Value (NPV) and Return on Investment
					(ROI) metrics.
				</p>
				<ul className="text-md font-light text-left mb-2 ml-8 list-disc">
					<li>Estimated Value within ±20% of asking price: Fair Value</li>
					<li>Estimated Value 20% above asking: Overvalued</li>
					<li>Estimated Value 20% below asking: Undervalued</li>
				</ul>
				<p className="text-md font-light text-left mb-2 ml-4">
					Sensitivity analysis tools are currently in development to complement
					this assessment.
				</p>
			</div>
			<ViewAllListings />
		</section>
	);
};

export default DocumentationPage;
